<?php
$title   = '3-Way Switching Ball Valve, 6,000 psi | TYA';
$desc    = '3-way switching instrument ball valve, 1/4" to 1", female NPT or twin-ferrule tube ends, 6,000 psi, for sample stream and line switching. Part numbers and quotes.';
$path    = 'ball-valves/3-way-switching-ball-valve';
$section = 'instr';
$extra   = '<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Product", "name": "3-Way Switching Instrument Ball Valve", "sku": "TYA-Series-04", "brand": {"@type": "Brand", "name": "Thank You America"}, "description": "One valve that switches flow between two lines, for example directing a sample to an analyzer or to a vent, or selecting between two supply sources. 180\\u00b0 of handle travel, and the handle points the way the fluid is going. 5-way switching versions are available on request.", "image": "https://tyallc.com/valves/assets/img/s04-photo.jpg", "category": "Industrial ball valves", "manufacturer": {"@type": "Organization", "name": "Thank You America LLC"}}</script>';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>ball-valves/">Instrumentation ball valves</a> / Series 04</div>
<section class="p-head"><div class="wrap p-grid">
 <div class="p-media" aria-label="3-way switching instrument ball valve manufacturers in Mexico" data-seo-loc><img src="<?= BASE ?>assets/img/p/bv-s04.jpg" alt="3-way switching ball valve with twin-ferrule tube ends on all three ports"></div>
 <div>
  <p class="p-num">Series 04</p>
  <h1>3-Way Switching Instrument Ball Valve</h1>
  <ul class="specline"><li class="hot">6,000 psi</li><li>1/4&quot; to 1&quot;</li><li>Female NPT/BSP or tube ends</li><li>3-way, 180° travel</li></ul>
  <p class="lede">One valve that switches flow between two lines, for example directing a sample to an analyzer or to a vent, or selecting between two supply sources. 180° of handle travel, and the handle points the way the fluid is going. 5-way switching versions are available on request.</p>
  <ul class="ticks"><li>Diverts or selects flow with 180° of handle travel</li><li>Handle indicates flow direction</li><li>Free-floating ball compensates for seat wear</li><li>Micro-finished ball; adjustable PTFE stem seal</li></ul>
  <p class="bestfor"><b>Best for:</b> stream switching, dual-source selection and vent diversion, with one valve instead of two.</p>
  <div class="cta-row"><a class="btn" href="#sizes">See part numbers</a><a class="btn ghost" href="<?= BASE ?>request-quote">Request a quote</a></div>
 </div>
</div></section>
<section class="section" id="sizes"><div class="wrap"><div class="section-head"><h2>Part numbers and dimensions</h2><p class="muted">Dimensions in mm, for reference only.</p></div><div class="tabs" role="tablist"><button class="tab" role="tab" id="t040" aria-controls="p040" aria-selected="true">Female NPT/BSP</button><button class="tab" role="tab" id="t041" aria-controls="p041" aria-selected="false">Tube ends</button></div><div class="tabpanel" role="tabpanel" id="p040" aria-labelledby="t040"><h3>Female ports, NPT or BSP (mm)</h3><div class="table-wrap"><table><caption class="skip">Female ports, NPT or BSP (mm)</caption><thead><tr><th>Part number</th><th>Size</th><th class=num>L</th><th class=num>H</th><th class=num>Orifice</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-BV-3V-S-04-FF</th><td>1/4&quot; female</td><td class=num>70</td><td class=num>32</td><td class=num>3</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-04-FF" data-desc="3-Way Switching Instrument Ball Valve, 1/4&quot; female, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-06-FF</th><td>3/8&quot; female</td><td class=num>72</td><td class=num>32</td><td class=num>8</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-06-FF" data-desc="3-Way Switching Instrument Ball Valve, 3/8&quot; female, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-08-FF</th><td>1/2&quot; female</td><td class=num>85</td><td class=num>38</td><td class=num>10</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-08-FF" data-desc="3-Way Switching Instrument Ball Valve, 1/2&quot; female, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-12-FF</th><td>3/4&quot; female</td><td class=num>98</td><td class=num>58</td><td class=num>16</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-12-FF" data-desc="3-Way Switching Instrument Ball Valve, 3/4&quot; female, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-16-FF</th><td>1&quot; female</td><td class=num>115</td><td class=num>58</td><td class=num>19</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-16-FF" data-desc="3-Way Switching Instrument Ball Valve, 1&quot; female, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">L and H as shown on the drawing. State NPT or BSP when ordering.</p></div><div class="tabpanel" role="tabpanel" id="p041" aria-labelledby="t041" hidden><h3>Twin-ferrule tube ends on all three ports (mm)</h3><div class="table-wrap"><table><caption class="skip">Twin-ferrule tube ends on all three ports (mm)</caption><thead><tr><th>Part number</th><th>Tube OD</th><th class=num>L</th><th class=num>H</th><th class=num>Orifice</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-BV-3V-S-04-OD</th><td>1/4&quot;</td><td class=num>78</td><td class=num>35</td><td class=num>5</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-04-OD" data-desc="3-Way Switching Instrument Ball Valve, 1/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-06-OD</th><td>3/8&quot;</td><td class=num>85</td><td class=num>35</td><td class=num>8</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-06-OD" data-desc="3-Way Switching Instrument Ball Valve, 3/8&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-08-OD</th><td>1/2&quot;</td><td class=num>102</td><td class=num>40</td><td class=num>10</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-08-OD" data-desc="3-Way Switching Instrument Ball Valve, 1/2&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-12-OD</th><td>3/4&quot;</td><td class=num>115</td><td class=num>60</td><td class=num>16</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-12-OD" data-desc="3-Way Switching Instrument Ball Valve, 3/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-3V-S-16-OD</th><td>1&quot;</td><td class=num>121</td><td class=num>60</td><td class=num>19</td><td><button class="add" data-series="Series 04" data-part="TYA-BV-3V-S-16-OD" data-desc="3-Way Switching Instrument Ball Valve, 1&quot;, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">Tube OD must match your tubing exactly.</p></div><div class="note warn"><b>Match the tube OD.</b> Tube ends must match your tubing's outside diameter exactly. Some inch and metric sizes look almost identical (6 mm and 1/4", 10 mm and 3/8", 12 mm and 1/2") but they are not interchangeable. Never mix nuts or ferrules between sizes, standards or manufacturers.</div></div></section><section class="section alt"><div class="wrap"><div class="section-head"><h2>Pressure rating by material</h2></div>
<div class="table-wrap"><table><thead><tr><th>Body material</th><th>Body CWP</th><th>With PTFE seats</th></tr></thead><tbody><tr><th scope='row'>316 stainless steel</th><td>6,000 psig (414 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Brass</th><td>3,000 psig (207 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Monel alloy 400</th><td>3,000 psig (207 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Hastelloy C-276</th><td>4,000 psig (276 bar)</td><td>1,500 psig (103 bar)</td></tr></tbody></table></div>
<p class="caption">The seat often sets the real pressure limit. With PTFE seats these valves are limited to 1,500 psig even when the body is rated higher. Tell us your pressure, temperature and fluid and we'll confirm the right seat.</p><div class="section-head"><h2>Construction and materials</h2></div>
<div class="two"><div><figure class="drawing" style="margin:0 0 16px" aria-label="3-way switching instrument ball valve suppliers in Houston" data-seo-loc><img src="<?= BASE ?>assets/img/s04-section.png" alt="3-way switching ball valve with female NPT ports" loading="lazy"><figcaption>Female port version</figcaption></figure><figure class="drawing" style="margin:0 0 16px" alt="3-way switching instrument ball valve suppliers in the USA" title="3-way switching instrument ball valve suppliers in the USA" data-seo-loc><img src="<?= BASE ?>assets/img/s04-tube-section.png" alt="3-way switching ball valve with twin-ferrule tube ends" loading="lazy"><figcaption>Tube-end version</figcaption></figure></div>
<div><div class="table-wrap"><table><thead><tr><th>#</th><th>Part</th><th>Material</th><th class="num">Qty</th></tr></thead><tbody><tr><td>1</td><th scope='row'>Body</th><td>A479-316L / B-16</td><td class='num'>1</td></tr><tr><td>2</td><th scope='row'>Ball</th><td>A479-316</td><td class='num'>1</td></tr><tr><td>3</td><th scope='row'>Seal</th><td>PTFE / POM</td><td class='num'>2</td></tr><tr><td>4</td><th scope='row'>O-ring</th><td>Viton / Buna-N</td><td class='num'>2</td></tr><tr><td>5</td><th scope='row'>Adaptor</th><td>A479-316L / B-16</td><td class='num'>2</td></tr><tr><td>6</td><th scope='row'>Spindle</th><td>A479-316</td><td class='num'>1</td></tr><tr><td>7</td><th scope='row'>O-ring</th><td>Viton / Buna-N</td><td class='num'>1</td></tr><tr><td>8</td><th scope='row'>Handle</th><td>Phenolic / SS lever</td><td class='num'>1</td></tr><tr><td>9</td><th scope='row'>Panel nut</th><td>A479-316L / B-16</td><td class='num'>1</td></tr><tr><td>10</td><th scope='row'>Gland nut</th><td>A479-316L / B-16</td><td class='num'>1</td></tr><tr><td>11</td><th scope='row'>Grub screw</th><td>Steel</td><td class='num'>1</td></tr></tbody></table></div>
<p class="caption">Same parts as the three-piece valve (Series 02). Tube-end versions add 3 nuts, 3 back ferrules and 3 front ferrules.</p>
<div class="note"><b>Servicing.</b> A slight weep at the stem can usually be cured in line by snugging the gland nut.</div></div></div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>
<section class="section alt"><div class="wrap" style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px"><a class="btn ghost" href="<?= BASE ?>ball-valves/angle-pattern-ball-valve">Previous: Series 03, Angle pattern</a><a class="btn ghost" href="<?= BASE ?>ball-valves/round-body-two-piece-ball-valve">Next: Series 05, Round body, two-piece</a></div></section><?php include __DIR__ . '/../includes/footer.php'; ?>
