<?php
$title   = 'Hex Body Two-Piece Ball Valve, 6,000 psi | TYA';
$desc    = 'Hex body two-piece stainless steel ball valve, 1/4" to 1", female NPT, male NPT or tube ends, 6,000 psi. Part numbers, dimensions and distributor quotes.';
$path    = 'ball-valves/hex-body-two-piece-ball-valve';
$section = 'instr';
$extra   = '<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Product", "name": "Hex Body Two-Piece Ball Valve", "sku": "TYA-Series-06", "brand": {"@type": "Brand", "name": "Thank You America"}, "description": "Twice the pressure class of the round body, in a hexagonal body you can hold securely with a wrench while making up threaded connections, so the torque goes into the joint, not the valve.", "image": "https://tyallc.com/valves/assets/img/s06-photo.jpg", "category": "Industrial ball valves", "manufacturer": {"@type": "Organization", "name": "Thank You America LLC"}}</script>';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>ball-valves/">Instrumentation ball valves</a> / Series 06</div>
<section class="p-head"><div class="wrap p-grid">
 <div class="p-media" alt="Hex body two-piece ball valve providers in Mexico" title="Hex body two-piece ball valve providers in Mexico" data-seo-loc><img src="<?= BASE ?>assets/img/p/bv-s06.jpg" alt="Hex body two-piece stainless steel ball valve with yellow lever handle"></div>
 <div>
  <p class="p-num">Series 06</p>
  <h1>Hex Body Two-Piece Ball Valve</h1>
  <ul class="specline"><li class="hot">6,000 psi</li><li>1/4&quot; to 1&quot;</li><li>Female NPT</li><li>Straight-through, 2-way</li></ul>
  <p class="lede">Twice the pressure class of the round body, in a hexagonal body you can hold securely with a wrench while making up threaded connections, so the torque goes into the joint, not the valve.</p>
  <ul class="ticks"><li>Free-floating ball compensates for seat wear</li><li>Micro-finished, hard-chrome-plated ball</li><li>Straight-through flow path for minimum pressure drop</li><li>Adjustable PTFE stem seal, serviceable in line</li></ul>
  <p class="bestfor"><b>Best for:</b> higher-pressure instrument, hydraulic and process lines.</p>
  <div class="cta-row"><a class="btn" href="#sizes">See part numbers</a><a class="btn ghost" href="<?= BASE ?>request-quote">Request a quote</a></div>
 </div>
</div></section>
<section class="section" id="sizes"><div class="wrap"><div class="section-head"><h2>Part numbers and dimensions</h2><p class="muted">Dimensions in mm, for reference only.</p></div><div class="table-wrap" style="margin-bottom:28px"><table><tbody><tr><th scope='row'>Rating</th><td style='white-space:normal'>6,000 psi (414 bar)</td></tr><tr><th scope='row'>Body materials</th><td style='white-space:normal'>316L / 316 / 304 / 304L SS, Monel, Inconel, carbon steel, duplex</td></tr><tr><th scope='row'>Service</th><td style='white-space:normal'>Liquid, gas, vapor</td></tr></tbody></table></div><h3>Sizes and dimensions (mm)</h3><div class="table-wrap"><table><caption class="skip">Sizes and dimensions (mm)</caption><thead><tr><th>Part number</th><th>Size</th><th class=num>L</th><th class=num>S</th><th class=num>H</th><th class=num>A</th><th class=num>B</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-HX2P-4-FF</th><td>1/4&quot;</td><td class=num>55</td><td class=num>27</td><td class=num>78.5</td><td class=num>53.5</td><td class=num>37.5</td><td><button class="add" data-series="Series 06" data-part="TYA-HX2P-4-FF" data-desc="Hex Body Two-Piece Ball Valve, 1/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-HX2P-6-FF</th><td>3/8&quot;</td><td class=num>55</td><td class=num>27</td><td class=num>78.5</td><td class=num>53.5</td><td class=num>37.5</td><td><button class="add" data-series="Series 06" data-part="TYA-HX2P-6-FF" data-desc="Hex Body Two-Piece Ball Valve, 3/8&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-HX2P-8-FF</th><td>1/2&quot;</td><td class=num>73</td><td class=num>36</td><td class=num>106</td><td class=num>69.5</td><td class=num>49</td><td><button class="add" data-series="Series 06" data-part="TYA-HX2P-8-FF" data-desc="Hex Body Two-Piece Ball Valve, 1/2&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-HX2P-12-FF</th><td>3/4&quot;</td><td class=num>78.5</td><td class=num>45</td><td class=num>157</td><td class=num>67.5</td><td class=num>45</td><td><button class="add" data-series="Series 06" data-part="TYA-HX2P-12-FF" data-desc="Hex Body Two-Piece Ball Valve, 3/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-HX2P-25-FF</th><td>1&quot;</td><td class=num>90</td><td class=num>55</td><td class=num>156</td><td class=num>81.5</td><td class=num>49.8</td><td><button class="add" data-series="Series 06" data-part="TYA-HX2P-25-FF" data-desc="Hex Body Two-Piece Ball Valve, 1&quot;, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">L length, S across flats, H handle reach, A overall height, B centerline to handle top. Female NPT both ends.</p></div></section><section class="section alt"><div class="wrap"><div class="section-head"><h2>Construction and materials</h2></div>
<div class="two"><div><figure class="drawing" style="margin:0 0 16px" aria-label="Hex body two-piece ball valve services in Houston" data-seo-loc><img src="<?= BASE ?>assets/img/s06-section.png" alt="Cross-section; callouts match the parts list" loading="lazy"><figcaption>Cross-section; callouts match the parts list</figcaption></figure></div>
<div><div class="table-wrap"><table><thead><tr><th>#</th><th>Part</th><th>Material</th><th class="num">Qty</th></tr></thead><tbody><tr><td>1</td><th scope='row'>Body</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>2</td><th scope='row'>Stem</th><td>A276-316</td><td class='num'>1</td></tr><tr><td>3</td><th scope='row'>Stem packing</th><td>PTFE / Graphoil</td><td class='num'>1</td></tr><tr><td>4</td><th scope='row'>Ball</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>5</td><th scope='row'>Ball seal</th><td>PTFE / Graphoil</td><td class='num'>2</td></tr><tr><td>6</td><th scope='row'>Gland packing</th><td>PTFE / Graphoil</td><td class='num'>As req.</td></tr><tr><td>7</td><th scope='row'>Gland washer</th><td>A276-316L / A105</td><td class='num'>As req.</td></tr><tr><td>8</td><th scope='row'>Adaptor</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>9</td><th scope='row'>Body seal</th><td>PTFE / Graphoil</td><td class='num'>1</td></tr><tr><td>10</td><th scope='row'>Lock pin</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>11</td><th scope='row'>Gland nut</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>12</td><th scope='row'>Handle</th><td>A276-316L / A105</td><td class='num'>1</td></tr><tr><td>13</td><th scope='row'>Lock nut</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>14</td><th scope='row'>Sleeve</th><td>PVC</td><td class='num'>1</td></tr></tbody></table></div>
<p class="caption">Same parts as Series 05.</p>
<div class="note"><b>Servicing.</b> A slight weep at the stem can usually be cured in line by snugging the gland nut.</div></div></div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>
<section class="section alt"><div class="wrap" style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px"><a class="btn ghost" href="<?= BASE ?>ball-valves/round-body-two-piece-ball-valve">Previous: Series 05, Round body, two-piece</a><a class="btn ghost" href="<?= BASE ?>ball-valves/square-body-ball-valve">Next: Series 07, Square body</a></div></section><?php include __DIR__ . '/../includes/footer.php'; ?>
