<?php
$title   = 'One-Piece Instrument Ball Valve, 6,000 psi | TYA';
$desc    = 'One-piece body stainless steel instrument ball valve, 1/8" to 1", female NPT or twin-ferrule tube ends, 6,000 psi, low dead volume. Part numbers and quotes.';
$path    = 'ball-valves/one-piece-body-ball-valve';
$section = 'instr';
$extra   = '<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Product", "name": "One-Piece Body Instrument Ball Valve", "sku": "TYA-Series-01", "brand": {"@type": "Brand", "name": "Thank You America"}, "description": "A compact valve with a single-piece body, so there are no body joints that could leak, and a very small internal volume, so little fluid is left trapped to contaminate the next sample. Panel mountable.", "image": "https://tyallc.com/valves/assets/img/s01-section.png", "category": "Industrial ball valves", "manufacturer": {"@type": "Organization", "name": "Thank You America LLC"}}</script>';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>ball-valves/">Instrumentation ball valves</a> / Series 01</div>
<section class="p-head"><div class="wrap p-grid">
 <div class="p-media"><img src="<?= BASE ?>assets/img/p/bv-s01.jpg" alt="Cross-section drawing of the one-piece body instrument ball valve"></div>
 <div>
  <p class="p-num">Series 01</p>
  <h1>One-Piece Body Instrument Ball Valve</h1>
  <ul class="specline"><li class="hot">6,000 psi</li><li>1/8&quot; to 1&quot;</li><li>Female NPT or tube ends</li><li>Straight-through, 2-way</li></ul>
  <p class="lede">A compact valve with a single-piece body, so there are no body joints that could leak, and a very small internal volume, so little fluid is left trapped to contaminate the next sample. Panel mountable.</p>
  <ul class="ticks"><li>Blow-out-proof, bottom-loaded stem</li><li>Low-torque nylon handle with brass insert</li><li>Full or reduced bore; PTFE, POM or Delrin seats</li><li>Panel nut included for mounting through a panel</li></ul>
  <p class="bestfor"><b>Best for:</b> analyzer and sampling systems that need the lowest dead volume, and control panels that need a compact, high-flow valve with clear flow indication.</p>
  <div class="cta-row"><a class="btn" href="#sizes">See part numbers</a><a class="btn ghost" href="<?= BASE ?>request-quote">Request a quote</a></div>
 </div>
</div></section>
<section class="section" id="sizes"><div class="wrap"><div class="section-head"><h2>Part numbers and dimensions</h2><p class="muted">Dimensions in mm, for reference only.</p></div><h3>Sizes and dimensions (mm)</h3><div class="table-wrap"><table><caption class="skip">Sizes and dimensions (mm)</caption><thead><tr><th>Part number</th><th>Size (tube OD / FNPT)</th><th class=num>L, FNPT</th><th class=num>L1, tube</th><th class=num>H</th><th class=num>Orifice</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-BV-2-S-02-FF / OD</th><td>1/8&quot;</td><td class=num>51</td><td class=num>51</td><td class=num>51</td><td class=num>3</td><td><button class="add" data-series="Series 01" data-part="TYA-BV-2-S-02-FF / OD" data-desc="One-Piece Body Instrument Ball Valve, 1/8&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-04-FF / OD</th><td>1/4&quot;</td><td class=num>56</td><td class=num>56</td><td class=num>56</td><td class=num>5</td><td><button class="add" data-series="Series 01" data-part="TYA-BV-2-S-04-FF / OD" data-desc="One-Piece Body Instrument Ball Valve, 1/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-06-FF / OD</th><td>3/8&quot;</td><td class=num>63</td><td class=num>66</td><td class=num>65</td><td class=num>8</td><td><button class="add" data-series="Series 01" data-part="TYA-BV-2-S-06-FF / OD" data-desc="One-Piece Body Instrument Ball Valve, 3/8&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-08-FF / OD</th><td>1/2&quot;</td><td class=num>90</td><td class=num>99</td><td class=num>99</td><td class=num>10</td><td><button class="add" data-series="Series 01" data-part="TYA-BV-2-S-08-FF / OD" data-desc="One-Piece Body Instrument Ball Valve, 1/2&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-12-FF / OD</th><td>3/4&quot;</td><td class=num>90</td><td class=num>99</td><td class=num>99</td><td class=num>16</td><td><button class="add" data-series="Series 01" data-part="TYA-BV-2-S-12-FF / OD" data-desc="One-Piece Body Instrument Ball Valve, 3/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-16-FF / OD</th><td>1&quot;</td><td class=num>115</td><td class=num>121</td><td class=num>112</td><td class=num>19</td><td><button class="add" data-series="Series 01" data-part="TYA-BV-2-S-16-FF / OD" data-desc="One-Piece Body Instrument Ball Valve, 1&quot;, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">Order with suffix FF for female NPT both ends or OD for tube ends. L = female NPT length, L1 = tube-end length, H = overall height. Reference only.</p></div></section><section class="section alt"><div class="wrap"><div class="section-head"><h2>Pressure rating by material</h2></div>
<div class="table-wrap"><table><thead><tr><th>Body material</th><th>Body CWP</th><th>With PTFE seats</th></tr></thead><tbody><tr><th scope='row'>316 stainless steel</th><td>6,000 psig (414 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Brass</th><td>1,000 psig (70 bar)</td><td>1,000 psig (70 bar)</td></tr><tr><th scope='row'>Monel alloy 400</th><td>3,000 psig (207 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Hastelloy C-276</th><td>4,000 psig (276 bar)</td><td>1,500 psig (103 bar)</td></tr></tbody></table></div>
<p class="caption">The seat often sets the real pressure limit. With PTFE seats these valves are limited to 1,500 psig even when the body is rated higher. Tell us your pressure, temperature and fluid and we'll confirm the right seat.</p><div class="section-head"><h2>Construction and materials</h2></div>
<div class="two"><div><figure class="drawing" style="margin:0 0 16px"><img src="<?= BASE ?>assets/img/s01-exploded.png" alt="Exploded view, top to bottom in the same order as the parts list" loading="lazy"><figcaption>Exploded view, top to bottom in the same order as the parts list</figcaption></figure></div>
<div><div class="table-wrap"><table><thead><tr><th>#</th><th>Part</th><th>Material</th><th class="num">Qty</th></tr></thead><tbody><tr><td>1</td><th scope='row'>Handle</th><td>Nylon, brass insert</td><td class='num'>1</td></tr><tr><td>2</td><th scope='row'>Set screw</th><td>Steel</td><td class='num'>1</td></tr><tr><td>3</td><th scope='row'>Packing bolt</th><td>A479-316L</td><td class='num'>1</td></tr><tr><td>4</td><th scope='row'>Panel nut</th><td>A479-316L</td><td class='num'>1</td></tr><tr><td>5</td><th scope='row'>Ball stem</th><td>A479-316L</td><td class='num'>1</td></tr><tr><td>6</td><th scope='row'>Packing</th><td>A479-316L</td><td class='num'>6</td></tr><tr><td>7</td><th scope='row'>Upper gland</th><td>A479-316L</td><td class='num'>1</td></tr><tr><td>8</td><th scope='row'>Lower gland</th><td>A479-316L</td><td class='num'>1</td></tr><tr><td>9</td><th scope='row'>Upper packing</th><td>PTFE</td><td class='num'>1</td></tr><tr><td>10</td><th scope='row'>Support ring</th><td>A479-316L</td><td class='num'>2</td></tr><tr><td>11</td><th scope='row'>Lower packing</th><td>PTFE</td><td class='num'>1</td></tr><tr><td>12</td><th scope='row'>Side discs</th><td>A479-316L</td><td class='num'>2</td></tr><tr><td>13</td><th scope='row'>Nut (tube-end versions)</th><td>A479-316L</td><td class='num'>2</td></tr><tr><td>14</td><th scope='row'>Back ferrule (tube-end versions)</th><td>A479-316L</td><td class='num'>2</td></tr><tr><td>15</td><th scope='row'>Front ferrule (tube-end versions)</th><td>A479-316L</td><td class='num'>2</td></tr><tr><td>16</td><th scope='row'>Body</th><td>A479-316L</td><td class='num'>1</td></tr></tbody></table></div>
<p class="caption"></p>
<div class="note"><b>Servicing.</b> A slight weep at the stem can usually be cured in line by snugging the packing bolt a small amount. To mount through a panel, remove the panel nut, pass the stem through the panel hole and refit the nut from the front.</div></div></div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>
<section class="section alt"><div class="wrap" style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px"><span></span><a class="btn ghost" href="<?= BASE ?>ball-valves/three-piece-instrument-ball-valve">Next: Series 02, Three-piece instrument</a></div></section><?php include __DIR__ . '/../includes/footer.php'; ?>
