<?php
$title   = 'Heavy-Duty 10,000 psi Hydraulic Ball Valve | 10,000 psi, 1/8&quot; to 1&quot; | Thank You America';
$desc    = 'Heavy-Duty 10,000 psi Hydraulic Ball Valve rated 10,000 psi, 1/8&quot; to 1&quot;, npt or sae ports. Part numbers, dimensions, materials and quotes from Thank You America, Houston TX.';
$path    = 'ball-valves/heavy-duty-hydraulic-ball-valve';
$section = 'instr';
$extra   = '<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Product", "name": "Heavy-Duty 10,000 psi Hydraulic Ball Valve", "sku": "TYA-Series-09", "brand": {"@type": "Brand", "name": "Thank You America"}, "description": "A simple, heavy-duty way to control hydraulic flow: a ported ball held between seals in a solid square housing. It needs no lubrication or routine maintenance, and every valve can be fully repaired.", "image": "https://tyallc.com/valves/assets/img/s09-photo.jpg", "category": "Industrial ball valves", "manufacturer": {"@type": "Organization", "name": "Thank You America LLC"}}</script>';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>ball-valves/">Instrumentation ball valves</a> / Series 09</div>
<section class="p-head"><div class="wrap p-grid">
 <div class="p-media"><img src="<?= BASE ?>assets/img/p/bv-s09.jpg" alt="Heavy-duty square body hydraulic ball valve with long lever handle"></div>
 <div>
  <p class="p-num">Series 09</p>
  <h1>Heavy-Duty 10,000 psi Hydraulic Ball Valve</h1>
  <ul class="specline"><li class="hot">10,000 psi</li><li>1/8&quot; to 1&quot;</li><li>NPT or SAE ports</li><li>Straight-through, 2-way</li></ul>
  <p class="lede">A simple, heavy-duty way to control hydraulic flow: a ported ball held between seals in a solid square housing. It needs no lubrication or routine maintenance, and every valve can be fully repaired.</p>
  <ul class="ticks"><li>Fully bidirectional, so it cannot be installed the wrong way round</li><li>No threads in the fluid path to shed debris</li><li>Hard-chrome, micro-smooth ball cuts friction and seat wear</li><li>Completely repairable; no lubrication needed for life</li></ul>
  <p class="bestfor"><b>Best for:</b> hydraulic power units, test benches and mobile hydraulics.</p>
  <div class="cta-row"><a class="btn" href="#sizes">See part numbers</a><a class="btn ghost" href="<?= BASE ?>request-quote">Request a quote</a></div>
 </div>
</div></section>
<section class="section" id="sizes"><div class="wrap"><div class="section-head"><h2>Part numbers and dimensions</h2><p class="muted">Dimensions in mm, for reference only.</p></div><div class="table-wrap" style="margin-bottom:28px"><table><tbody><tr><th scope='row'>Rating, seat, ball</th><td style='white-space:normal'>10,000 psi (689 bar), soft seat, hard-chrome ball</td></tr><tr><th scope='row'>Body materials</th><td style='white-space:normal'>316 / 304 SS, Monel, Inconel, carbon steel, duplex</td></tr><tr><th scope='row'>NPT or SAE?</th><td style='white-space:normal'>NPT seals on the tapered thread with sealant; SAE seals on an O-ring with no sealant in the system.</td></tr></tbody></table></div><div class="tabs" role="tablist"><button class="tab" role="tab" id="t090" aria-controls="p090" aria-selected="true">Ports and length</button><button class="tab" role="tab" id="t091" aria-controls="p091" aria-selected="false">Body and handle</button></div><div class="tabpanel" role="tabpanel" id="p090" aria-labelledby="t090"><h3>Ports and length (mm)</h3><div class="table-wrap"><table><caption class="skip">Ports and length (mm)</caption><thead><tr><th>Size</th><th>d, NPT</th><th class=num>d, SAE</th><th class=num>i, NPT</th><th class=num>i, SAE</th><th class=num>L</th><th class=num>LW, NPT</th><th class=num>LW, SAE</th></tr></thead><tbody><tr><th scope='row'>1/8&quot;</th><td>1/8–27</td><td class=num>5/16–24</td><td class=num>12.95</td><td class=num>—</td><td class=num>—</td><td class=num>6.10</td><td class=num>—</td></tr><tr><th scope='row'>1/4&quot;</th><td>1/4–18</td><td class=num>7/16–20</td><td class=num>17.02</td><td class=num>13.97</td><td class=num>69.00</td><td class=num>6.10</td><td class=num>5.08</td></tr><tr><th scope='row'>3/8&quot;</th><td>3/8–18</td><td class=num>9/16–18</td><td class=num>17.53</td><td class=num>15.49</td><td class=num>72.00</td><td class=num>10.00</td><td class=num>10.00</td></tr><tr><th scope='row'>1/2&quot;</th><td>1/2–14</td><td class=num>3/4–16</td><td class=num>15.80</td><td class=num>17.53</td><td class=num>83.06</td><td class=num>13.00</td><td class=num>13.00</td></tr><tr><th scope='row'>3/4&quot;</th><td>3/4–14</td><td class=num>1-1/16–12</td><td class=num>18.00</td><td class=num>23.11</td><td class=num>95.00</td><td class=num>20.00</td><td class=num>20.00</td></tr><tr><th scope='row'>1&quot;</th><td>1–11-1/2</td><td class=num>1-5/16–12</td><td class=num>27.69</td><td class=num>20.00</td><td class=num>113.00</td><td class=num>25.00</td><td class=num>25.00</td></tr><tr><th scope='row'>1&quot; H</th><td>1-1/2–11-1/2</td><td class=num>1-5/8–12</td><td class=num>20.00</td><td class=num>20.00</td><td class=num>113.00</td><td class=num>25.00</td><td class=num>25.00</td></tr></tbody></table></div>
<p class="caption">d port thread size, i thread depth, LW port bore, L overall length.</p></div><div class="tabpanel" role="tabpanel" id="p091" aria-labelledby="t091" hidden><h3>Body and handle (mm)</h3><div class="table-wrap"><table><caption class="skip">Body and handle (mm)</caption><thead><tr><th>Size</th><th>I</th><th class=num>B</th><th class=num>H</th><th class=num>h</th><th class=num>m</th><th class=num>V</th><th class=num>SW</th><th class=num>K1</th><th class=num>K2</th></tr></thead><tbody><tr><th scope='row'>1/8&quot;</th><td>39.88</td><td class=num>25.91</td><td class=num>46.99</td><td class=num>33.02</td><td class=num>13.46</td><td class=num>10.92</td><td class=num>9</td><td class=num>150.11</td><td class=num>115.06</td></tr><tr><th scope='row'>1/4&quot;</th><td>39.88</td><td class=num>25.91</td><td class=num>46.99</td><td class=num>33.02</td><td class=num>13.46</td><td class=num>10.92</td><td class=num>9</td><td class=num>150.11</td><td class=num>115.06</td></tr><tr><th scope='row'>3/8&quot;</th><td>42.93</td><td class=num>32.00</td><td class=num>52.07</td><td class=num>38.10</td><td class=num>17.53</td><td class=num>10.92</td><td class=num>9</td><td class=num>150.11</td><td class=num>115.06</td></tr><tr><th scope='row'>1/2&quot;</th><td>48.01</td><td class=num>35.05</td><td class=num>54.10</td><td class=num>39.88</td><td class=num>19.05</td><td class=num>10.92</td><td class=num>9</td><td class=num>150.11</td><td class=num>115.06</td></tr><tr><th scope='row'>3/4&quot;</th><td>61.98</td><td class=num>49.02</td><td class=num>74.93</td><td class=num>56.90</td><td class=num>24.38</td><td class=num>13.97</td><td class=num>14</td><td class=num>199.90</td><td class=num>171.00</td></tr><tr><th scope='row'>1&quot;</th><td>66.04</td><td class=num>57.91</td><td class=num>83.06</td><td class=num>65.02</td><td class=num>29.46</td><td class=num>13.97</td><td class=num>14</td><td class=num>199.90</td><td class=num>160.00</td></tr><tr><th scope='row'>1&quot; H</th><td>74.00</td><td class=num>70.00</td><td class=num>88.00</td><td class=num>70.00</td><td class=num>34.50</td><td class=num>14.00</td><td class=num>14</td><td class=num>200.00</td><td class=num>160.00</td></tr></tbody></table></div>
<p class="caption">I body length, B body width, H height to top of handle hub, h body height, m bore centerline to base, V handle hub above body, SW stem across flats, K1 and K2 handle reach in two positions.</p></div><div class="note"><b>Add a size to your quote.</b> Say NPT or SAE ports in the quote notes.<div style="margin-top:10px;display:flex;flex-wrap:wrap;align-items:center;gap:8px 0"><button class="add" data-series="Series 09" data-part="Series 09 1/8&quot;" data-desc="Heavy-Duty 10,000 psi Hydraulic Ball Valve, 1/8&quot; (state NPT or SAE)">Add to quote</button> <span style="margin-right:14px">1/8&quot;</span><button class="add" data-series="Series 09" data-part="Series 09 1/4&quot;" data-desc="Heavy-Duty 10,000 psi Hydraulic Ball Valve, 1/4&quot; (state NPT or SAE)">Add to quote</button> <span style="margin-right:14px">1/4&quot;</span><button class="add" data-series="Series 09" data-part="Series 09 3/8&quot;" data-desc="Heavy-Duty 10,000 psi Hydraulic Ball Valve, 3/8&quot; (state NPT or SAE)">Add to quote</button> <span style="margin-right:14px">3/8&quot;</span><button class="add" data-series="Series 09" data-part="Series 09 1/2&quot;" data-desc="Heavy-Duty 10,000 psi Hydraulic Ball Valve, 1/2&quot; (state NPT or SAE)">Add to quote</button> <span style="margin-right:14px">1/2&quot;</span><button class="add" data-series="Series 09" data-part="Series 09 3/4&quot;" data-desc="Heavy-Duty 10,000 psi Hydraulic Ball Valve, 3/4&quot; (state NPT or SAE)">Add to quote</button> <span style="margin-right:14px">3/4&quot;</span><button class="add" data-series="Series 09" data-part="Series 09 1&quot;" data-desc="Heavy-Duty 10,000 psi Hydraulic Ball Valve, 1&quot; (state NPT or SAE)">Add to quote</button> <span style="margin-right:14px">1&quot;</span><button class="add" data-series="Series 09" data-part="Series 09 1&quot; H" data-desc="Heavy-Duty 10,000 psi Hydraulic Ball Valve, 1&quot; H (state NPT or SAE)">Add to quote</button> <span style="margin-right:14px">1&quot; H</span></div></div></div></section><section class="section alt"><div class="wrap"><div class="section-head"><h2>Dimensional drawing</h2></div><figure class="drawing" style="margin:0 0 16px"><img src="<?= BASE ?>assets/img/s09-drawing.png" alt="Dimensional drawing; letters match the tables" loading="lazy"><figcaption>Dimensional drawing; letters match the tables</figcaption></figure><div class="note"><b>Servicing.</b> Depressurize and drain the line before loosening any end connection.</div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>
<section class="section alt"><div class="wrap" style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px"><a class="btn ghost" href="<?= BASE ?>ball-valves/10000-psi-hex-body-ball-valve">Previous: Series 08, 10,000 psi hex body</a><a class="btn ghost" href="<?= BASE ?>ball-valves/">All ball valves</a></div></section><?php include __DIR__ . '/../includes/footer.php'; ?>
