<?php
$title   = 'Square Body Ball Valve | 6,000 psi, 1/4&quot; to 1&quot; | Thank You America';
$desc    = 'Square Body Ball Valve rated 6,000 psi, 1/4&quot; to 1&quot;, female npt (tube, socket weld on request). Part numbers, dimensions, materials and quotes from Thank You America, Houston TX.';
$path    = 'ball-valves/square-body-ball-valve';
$section = 'instr';
$extra   = '<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Product", "name": "Square Body Ball Valve", "sku": "TYA-Series-07", "brand": {"@type": "Brand", "name": "Thank You America"}, "description": "An internally loaded, blow-out-proof stem and a floating ball give positive shut-off in a compact square body. The hard-chromed ball reduces friction, so the valve stays easy to turn throughout its life. Photo shows optional tube ends.", "image": "https://tyallc.com/valves/assets/img/s07-photo.jpg", "category": "Industrial ball valves", "manufacturer": {"@type": "Organization", "name": "Thank You America LLC"}}</script>';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>ball-valves/">Instrumentation ball valves</a> / Series 07</div>
<section class="p-head"><div class="wrap p-grid">
 <div class="p-media"><img src="<?= BASE ?>assets/img/p/bv-s07.jpg" alt="Square body ball valve shown with optional tube ends"></div>
 <div>
  <p class="p-num">Series 07</p>
  <h1>Square Body Ball Valve</h1>
  <ul class="specline"><li class="hot">6,000 psi</li><li>1/4&quot; to 1&quot;</li><li>Female NPT (tube, socket weld on request)</li><li>Straight-through, 2-way</li></ul>
  <p class="lede">An internally loaded, blow-out-proof stem and a floating ball give positive shut-off in a compact square body. The hard-chromed ball reduces friction, so the valve stays easy to turn throughout its life. Photo shows optional tube ends.</p>
  <ul class="ticks"><li>Hard-chromed ball for low friction and low torque</li><li>Blow-out-proof, internally loaded stem</li><li>PTFE and Graphoil gland packings</li><li>Adjustable stem seal; other materials and ends on request</li></ul>
  <p class="bestfor"><b>Best for:</b> demanding process and utility service where you want a rugged, flat-sided body that mounts and wrenches easily.</p>
  <div class="cta-row"><a class="btn" href="#sizes">See part numbers</a><a class="btn ghost" href="<?= BASE ?>request-quote">Request a quote</a></div>
 </div>
</div></section>
<section class="section" id="sizes"><div class="wrap"><div class="section-head"><h2>Part numbers and dimensions</h2><p class="muted">Dimensions in mm, for reference only.</p></div><div class="table-wrap" style="margin-bottom:28px"><table><tbody><tr><th scope='row'>Rating</th><td style='white-space:normal'>6,000 psi (414 bar)</td></tr><tr><th scope='row'>Body materials</th><td style='white-space:normal'>316L / 316 / 304 / 304L SS, Monel, Inconel, carbon steel, duplex</td></tr><tr><th scope='row'>Ends</th><td style='white-space:normal'>Female NPT; tube and socket weld on request</td></tr></tbody></table></div><h3>Sizes and dimensions (mm)</h3><div class="table-wrap"><table><caption class="skip">Sizes and dimensions (mm)</caption><thead><tr><th>Part number</th><th>Size</th><th class=num>A</th><th class=num>B</th><th class=num>L</th><th class=num>H</th><th class=num>T</th><th class=num>Orifice</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-SQ2P-4-FF</th><td>1/4&quot;</td><td class=num>30</td><td class=num>33</td><td class=num>76</td><td class=num>110</td><td class=num>49</td><td class=num>4.8</td><td><button class="add" data-series="Series 07" data-part="TYA-SQ2P-4-FF" data-desc="Square Body Ball Valve, 1/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-SQ2P-6-FF</th><td>3/8&quot;</td><td class=num>30</td><td class=num>33</td><td class=num>76</td><td class=num>110</td><td class=num>49</td><td class=num>7</td><td><button class="add" data-series="Series 07" data-part="TYA-SQ2P-6-FF" data-desc="Square Body Ball Valve, 3/8&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-SQ2P-8-FF</th><td>1/2&quot;</td><td class=num>35</td><td class=num>38</td><td class=num>96</td><td class=num>180</td><td class=num>64</td><td class=num>9.5</td><td><button class="add" data-series="Series 07" data-part="TYA-SQ2P-8-FF" data-desc="Square Body Ball Valve, 1/2&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-SQ2P-12-FF</th><td>3/4&quot;</td><td class=num>43</td><td class=num>49</td><td class=num>108</td><td class=num>180</td><td class=num>67</td><td class=num>12</td><td><button class="add" data-series="Series 07" data-part="TYA-SQ2P-12-FF" data-desc="Square Body Ball Valve, 3/4&quot;, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-SQ2P-25-FF</th><td>1&quot;</td><td class=num>50</td><td class=num>56</td><td class=num>125</td><td class=num>180</td><td class=num>70</td><td class=num>20</td><td><button class="add" data-series="Series 07" data-part="TYA-SQ2P-25-FF" data-desc="Square Body Ball Valve, 1&quot;, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">A × B square body section, L overall length, H handle reach from stem center, T bore centerline to top of handle.</p></div></section><section class="section alt"><div class="wrap"><div class="section-head"><h2>Construction and materials</h2></div>
<div class="two"><div><figure class="drawing" style="margin:0 0 16px"><img src="<?= BASE ?>assets/img/s07-section.png" alt="Cross-section; callouts match the parts list" loading="lazy"><figcaption>Cross-section; callouts match the parts list</figcaption></figure></div>
<div><div class="table-wrap"><table><thead><tr><th>#</th><th>Part</th><th>Material</th><th class="num">Qty</th></tr></thead><tbody><tr><td>1</td><th scope='row'>Body</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>2</td><th scope='row'>Stem</th><td>A276-316</td><td class='num'>1</td></tr><tr><td>3</td><th scope='row'>Stem packing</th><td>PTFE / Graphoil</td><td class='num'>1</td></tr><tr><td>4</td><th scope='row'>Ball</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>5</td><th scope='row'>Ball seal</th><td>PTFE / Graphoil</td><td class='num'>2</td></tr><tr><td>6</td><th scope='row'>Gland packing</th><td>PTFE / Graphoil</td><td class='num'>As req.</td></tr><tr><td>7</td><th scope='row'>Gland washer</th><td>A276-316L / A105</td><td class='num'>As req.</td></tr><tr><td>8</td><th scope='row'>Adaptor</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>9</td><th scope='row'>Body seal</th><td>PTFE / Graphoil</td><td class='num'>1</td></tr><tr><td>10</td><th scope='row'>Lock pin</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>11</td><th scope='row'>Gland nut</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>12</td><th scope='row'>Handle</th><td>A276-316L / A105</td><td class='num'>1</td></tr><tr><td>13</td><th scope='row'>Lock nut</th><td>A479-316L / A105</td><td class='num'>1</td></tr><tr><td>14</td><th scope='row'>Sleeve</th><td>PVC</td><td class='num'>1</td></tr></tbody></table></div>
<p class="caption">Same parts as Series 05.</p>
<div class="note"><b>Servicing.</b> A slight weep at the stem can usually be cured in line by snugging the gland nut.</div></div></div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>
<section class="section alt"><div class="wrap" style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px"><a class="btn ghost" href="<?= BASE ?>ball-valves/hex-body-two-piece-ball-valve">Previous: Series 06, Hex body, two-piece</a><a class="btn ghost" href="<?= BASE ?>ball-valves/10000-psi-hex-body-ball-valve">Next: Series 08, 10,000 psi hex body</a></div></section><?php include __DIR__ . '/../includes/footer.php'; ?>
