<?php
$title   = 'Three-Piece Instrument Ball Valve | 6,000 psi, 1/8&quot; to 1&quot;, 4 to 25 mm | Thank You America';
$desc    = 'Three-Piece Instrument Ball Valve rated 6,000 psi, 1/8&quot; to 1&quot;, 4 to 25 mm, female npt or twin-ferrule tube ends. Part numbers, dimensions, materials and quotes from Thank You America, Houston TX.';
$path    = 'ball-valves/three-piece-instrument-ball-valve';
$section = 'instr';
$extra   = '<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Product", "name": "Three-Piece Instrument Ball Valve", "sku": "TYA-Series-02", "brand": {"@type": "Brand", "name": "Thank You America"}, "description": "A square body with two O-ring-sealed end adaptors and a free-floating ball. The straight-through bore keeps pressure drop low, and a 90\\u00b0 turn takes it from fully open to fully closed. Available with female NPT ports or with twin-ferrule tube ends that connect straight to your tubing, with no taper threads and no thread sealant.", "image": "https://tyallc.com/valves/assets/img/s02-photo.jpg", "category": "Industrial ball valves", "manufacturer": {"@type": "Organization", "name": "Thank You America LLC"}}</script>';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>ball-valves/">Instrumentation ball valves</a> / Series 02</div>
<section class="p-head"><div class="wrap p-grid">
 <div class="p-media"><img src="<?= BASE ?>assets/img/p/bv-s02.jpg" alt="Three-piece stainless steel instrument ball valve with female NPT ends"></div>
 <div>
  <p class="p-num">Series 02</p>
  <h1>Three-Piece Instrument Ball Valve</h1>
  <ul class="specline"><li class="hot">6,000 psi</li><li>1/8&quot; to 1&quot;, 4 to 25 mm</li><li>Female NPT or twin-ferrule tube ends</li><li>Straight-through, 2-way</li></ul>
  <p class="lede">A square body with two O-ring-sealed end adaptors and a free-floating ball. The straight-through bore keeps pressure drop low, and a 90° turn takes it from fully open to fully closed. Available with female NPT ports or with twin-ferrule tube ends that connect straight to your tubing, with no taper threads and no thread sealant.</p>
  <ul class="ticks"><li>Free-floating ball compensates for seat wear</li><li>Micro-finished ball for a positive seal</li><li>90° actuation with phenolic handle or SS lever</li><li>Adjustable PTFE stem seal, serviceable in line</li></ul>
  <p class="bestfor"><b>Best for:</b> instrument, impulse and sample lines.</p>
  <div class="cta-row"><a class="btn" href="#sizes">See part numbers</a><a class="btn ghost" href="<?= BASE ?>request-quote">Request a quote</a></div>
 </div>
</div></section>
<section class="section" id="sizes"><div class="wrap"><div class="section-head"><h2>Part numbers and dimensions</h2><p class="muted">Dimensions in mm, for reference only.</p></div><div class="tabs" role="tablist"><button class="tab" role="tab" id="t020" aria-controls="p020" aria-selected="true">Female NPT</button><button class="tab" role="tab" id="t021" aria-controls="p021" aria-selected="false">Fractional tube OD</button><button class="tab" role="tab" id="t022" aria-controls="p022" aria-selected="false">Metric tube OD</button></div><div class="tabpanel" role="tabpanel" id="p020" aria-labelledby="t020"><h3>Female NPT × female NPT (mm)</h3><div class="table-wrap"><table><caption class="skip">Female NPT × female NPT (mm)</caption><thead><tr><th>Part number</th><th>Size</th><th class=num>L</th><th class=num>H</th><th class=num>Orifice</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-BV-2-S-02-FF</th><td>1/8&quot; female NPT</td><td class=num>70</td><td class=num>50</td><td class=num>3</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-02-FF" data-desc="Three-Piece Instrument Ball Valve, 1/8&quot; female NPT, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-04-FF</th><td>1/4&quot; female NPT</td><td class=num>70</td><td class=num>50</td><td class=num>5</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-04-FF" data-desc="Three-Piece Instrument Ball Valve, 1/4&quot; female NPT, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-06-FF</th><td>3/8&quot; female NPT</td><td class=num>72</td><td class=num>50</td><td class=num>8</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-06-FF" data-desc="Three-Piece Instrument Ball Valve, 3/8&quot; female NPT, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-08-FF</th><td>1/2&quot; female NPT</td><td class=num>85</td><td class=num>60</td><td class=num>10</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-08-FF" data-desc="Three-Piece Instrument Ball Valve, 1/2&quot; female NPT, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-12-FF</th><td>3/4&quot; female NPT</td><td class=num>98</td><td class=num>60</td><td class=num>16</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-12-FF" data-desc="Three-Piece Instrument Ball Valve, 3/4&quot; female NPT, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-16-FF</th><td>1&quot; female NPT</td><td class=num>115</td><td class=num>70</td><td class=num>19</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-16-FF" data-desc="Three-Piece Instrument Ball Valve, 1&quot; female NPT, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">L overall length, H overall height. Reference only. Brass (B-16) option available.</p></div><div class="tabpanel" role="tabpanel" id="p021" aria-labelledby="t021" hidden><h3>Twin-ferrule tube ends, fractional OD (mm)</h3><div class="table-wrap"><table><caption class="skip">Twin-ferrule tube ends, fractional OD (mm)</caption><thead><tr><th>Part number</th><th>Tube OD</th><th class=num>L</th><th class=num>H</th><th class=num>Orifice</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-BV-2-S-02-OD</th><td>1/8&quot; OD</td><td class=num>78</td><td class=num>50</td><td class=num>3</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-02-OD" data-desc="Three-Piece Instrument Ball Valve, 1/8&quot; OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-04-OD</th><td>1/4&quot; OD</td><td class=num>78</td><td class=num>50</td><td class=num>5</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-04-OD" data-desc="Three-Piece Instrument Ball Valve, 1/4&quot; OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-05-OD</th><td>5/16&quot; OD</td><td class=num>78</td><td class=num>50</td><td class=num>5</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-05-OD" data-desc="Three-Piece Instrument Ball Valve, 5/16&quot; OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-06-OD</th><td>3/8&quot; OD</td><td class=num>85</td><td class=num>50</td><td class=num>8</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-06-OD" data-desc="Three-Piece Instrument Ball Valve, 3/8&quot; OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-08-OD</th><td>1/2&quot; OD</td><td class=num>102</td><td class=num>60</td><td class=num>10</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-08-OD" data-desc="Three-Piece Instrument Ball Valve, 1/2&quot; OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-10-OD</th><td>5/8&quot; OD</td><td class=num>97</td><td class=num>63</td><td class=num>10</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-10-OD" data-desc="Three-Piece Instrument Ball Valve, 5/8&quot; OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-12-OD</th><td>3/4&quot; OD</td><td class=num>115</td><td class=num>60</td><td class=num>16</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-12-OD" data-desc="Three-Piece Instrument Ball Valve, 3/4&quot; OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-16-OD</th><td>1&quot; OD</td><td class=num>121</td><td class=num>73</td><td class=num>19</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-16-OD" data-desc="Three-Piece Instrument Ball Valve, 1&quot; OD, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">Request a certified drawing before finalizing a design.</p></div><div class="tabpanel" role="tabpanel" id="p022" aria-labelledby="t022" hidden><h3>Twin-ferrule tube ends, metric OD (mm)</h3><div class="table-wrap"><table><caption class="skip">Twin-ferrule tube ends, metric OD (mm)</caption><thead><tr><th>Part number</th><th>Tube OD</th><th class=num>L</th><th class=num>H</th><th class=num>Orifice</th><th><span class='small'>Quote</span></th></tr></thead><tbody><tr><th scope='row'>TYA-BV-2-S-M04-OD</th><td>4 mm OD</td><td class=num>78</td><td class=num>50</td><td class=num>3</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M04-OD" data-desc="Three-Piece Instrument Ball Valve, 4 mm OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-M06-OD</th><td>6 mm OD</td><td class=num>78</td><td class=num>50</td><td class=num>5</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M06-OD" data-desc="Three-Piece Instrument Ball Valve, 6 mm OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-M08-OD</th><td>8 mm OD</td><td class=num>78</td><td class=num>50</td><td class=num>5</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M08-OD" data-desc="Three-Piece Instrument Ball Valve, 8 mm OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-M10-OD</th><td>10 mm OD</td><td class=num>85</td><td class=num>50</td><td class=num>8</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M10-OD" data-desc="Three-Piece Instrument Ball Valve, 10 mm OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-M12-OD</th><td>12 mm OD</td><td class=num>102</td><td class=num>60</td><td class=num>10</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M12-OD" data-desc="Three-Piece Instrument Ball Valve, 12 mm OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-M16-OD</th><td>16 mm OD</td><td class=num>97</td><td class=num>63</td><td class=num>10</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M16-OD" data-desc="Three-Piece Instrument Ball Valve, 16 mm OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-M20-OD</th><td>20 mm OD</td><td class=num>115</td><td class=num>60</td><td class=num>16</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M20-OD" data-desc="Three-Piece Instrument Ball Valve, 20 mm OD, 6,000 psi">Add to quote</button></td></tr><tr><th scope='row'>TYA-BV-2-S-M25-OD</th><td>25 mm OD</td><td class=num>121</td><td class=num>73</td><td class=num>19</td><td><button class="add" data-series="Series 02" data-part="TYA-BV-2-S-M25-OD" data-desc="Three-Piece Instrument Ball Valve, 25 mm OD, 6,000 psi">Add to quote</button></td></tr></tbody></table></div>
<p class="caption">Metric part numbers carry an M before the size.</p></div><div class="note warn"><b>Match the tube OD.</b> Tube ends must match your tubing's outside diameter exactly. Some inch and metric sizes look almost identical (6 mm and 1/4", 10 mm and 3/8", 12 mm and 1/2") but they are not interchangeable. Never mix nuts or ferrules between sizes, standards or manufacturers.</div></div></section><section class="section alt"><div class="wrap"><div class="section-head"><h2>Pressure rating by material</h2></div>
<div class="table-wrap"><table><thead><tr><th>Body material</th><th>Body CWP</th><th>With PTFE seats</th></tr></thead><tbody><tr><th scope='row'>316 stainless steel</th><td>6,000 psig (414 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Brass</th><td>3,000 psig (207 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Monel alloy 400</th><td>3,000 psig (207 bar)</td><td>1,500 psig (103 bar)</td></tr><tr><th scope='row'>Hastelloy C-276</th><td>4,000 psig (276 bar)</td><td>1,500 psig (103 bar)</td></tr></tbody></table></div>
<p class="caption">The seat often sets the real pressure limit. With PTFE seats these valves are limited to 1,500 psig even when the body is rated higher. Tell us your pressure, temperature and fluid and we'll confirm the right seat.</p><div class="section-head"><h2>Construction and materials</h2></div>
<div class="two"><div><figure class="drawing" style="margin:0 0 16px"><img src="<?= BASE ?>assets/img/s02-section.png" alt="Female NPT version, callouts match the parts list" loading="lazy"><figcaption>Female NPT version, callouts match the parts list</figcaption></figure><figure class="drawing" style="margin:0 0 16px"><img src="<?= BASE ?>assets/img/s02-tube-section.png" alt="Tube-end version with nut and twin ferrules" loading="lazy"><figcaption>Tube-end version with nut and twin ferrules</figcaption></figure></div>
<div><div class="table-wrap"><table><thead><tr><th>#</th><th>Part</th><th>Material</th><th class="num">Qty</th></tr></thead><tbody><tr><td>1</td><th scope='row'>Body</th><td>A479-316L / B-16</td><td class='num'>1</td></tr><tr><td>2</td><th scope='row'>Ball</th><td>A479-316</td><td class='num'>1</td></tr><tr><td>3</td><th scope='row'>Seal</th><td>PTFE / POM</td><td class='num'>2</td></tr><tr><td>4</td><th scope='row'>O-ring</th><td>Viton / Buna-N</td><td class='num'>2</td></tr><tr><td>5</td><th scope='row'>Adaptor</th><td>A479-316L / B-16</td><td class='num'>2</td></tr><tr><td>6</td><th scope='row'>Spindle</th><td>A479-316</td><td class='num'>1</td></tr><tr><td>7</td><th scope='row'>O-ring</th><td>Viton / Buna-N</td><td class='num'>1</td></tr><tr><td>8</td><th scope='row'>Handle</th><td>Phenolic / SS lever</td><td class='num'>1</td></tr><tr><td>9</td><th scope='row'>Panel nut</th><td>A479-316L / B-16</td><td class='num'>1</td></tr><tr><td>10</td><th scope='row'>Gland nut</th><td>A479-316L / B-16</td><td class='num'>1</td></tr><tr><td>11</td><th scope='row'>Grub screw</th><td>Steel</td><td class='num'>1</td></tr></tbody></table></div>
<p class="caption">Tube-end versions add 2 nuts, 2 back ferrules and 2 front ferrules in A479-316L / B-16.</p>
<div class="note"><b>Servicing.</b> A slight weep at the stem can usually be cured in line by snugging the gland nut. Depressurize the line before loosening any tube nut.</div></div></div><figure class="drawing" style="margin:24px 0 0;max-width:520px"><img src="<?= BASE ?>assets/img/s02-tube-photo.jpg" alt="Three-piece instrument ball valve with twin-ferrule tube ends" loading="lazy"><figcaption>Three-piece instrument ball valve with twin-ferrule tube ends</figcaption></figure></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>
<section class="section alt"><div class="wrap" style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px"><a class="btn ghost" href="<?= BASE ?>ball-valves/one-piece-body-ball-valve">Previous: Series 01, One-piece body</a><a class="btn ghost" href="<?= BASE ?>ball-valves/angle-pattern-ball-valve">Next: Series 03, Angle pattern</a></div></section><?php include __DIR__ . '/../includes/footer.php'; ?>
