<?php
$title   = '2-Valve Manifold, 6,000 / 10,000 psi | TYA';
$desc    = '2-valve instrument manifolds for pressure gauges, switches and static pressure transmitters, 6,000 or 10,000 psi, 8 models. Part numbers and quotes.';
$path    = 'manifold-valves/2-valve-manifold';
$section = 'valves';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>manifold-valves/">Manifold valves</a> / 2-Valve Manifolds</div><section class="hero"><div class="wrap">
 <h1>2-Valve Manifolds</h1><div class="rule" aria-hidden="true"></div>
 <p class="lede">Isolation plus calibration / vent for gauges, pressure switches and static pressure transmitters. Hard seat 10,000 psi or soft seat 6,000 psi, in 316 stainless and alloys.</p><div class="hero-actions"><a class="btn" href="#models">See all models</a><a class="btn ghost" href="<?= BASE ?>assets/catalogs/TYA-Manifold-Valve-Catalog.pdf" data-catalog="manifold">Download the manifold &amp; gauge root valves catalog (PDF)</a></div>
</div></section><section class="section"><div class="wrap"><h2 id="models">Models</h2><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2vmr">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2vmr.jpg" alt="2V pipe to pipe manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2VMR-P8SS-HS</p><h3>2V pipe to pipe manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Single block with female screwed inlet and outlet ports combining an isolation valve and a calibration / vent valve. Generally used on static pressure transmitters, switches or gauges.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2VMR-P8SS-HS" data-desc="2V pipe to pipe manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2vsr">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2vsr.jpg" alt="2V pipe to pipe (side vent) manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2VSR-P8SS-HS</p><h3>2V pipe to pipe (side vent) manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Pipe-to-pipe 2-valve manifold in a single block, with female screwed inlet and outlet ports and a side vent, combining isolation and calibration / vent.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2VSR-P8SS-HS" data-desc="2V pipe to pipe (side vent) manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2vl1">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2vl1.jpg" alt="2V remote mount manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2VL1-P8SS-HS</p><h3>2V remote mount manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Remote-mount 2-valve manifold for connecting the impulse line to transmitters: easy isolation, calibration and block and bleed for gauges, pressure switches and static pressure instruments.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(M) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2VL1-P8SS-HS" data-desc="2V remote mount manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2vl2">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2vl2.jpg" alt="2V remote mount (vent near male instrument side) manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2VL2-P8SS-HS</p><h3>2V remote mount (vent near male instrument side) manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Remote-mount 2-valve manifold with the vent positioned near the male instrument connection side.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(M) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2VL2-P8SS-HS" data-desc="2V remote mount (vent near male instrument side) manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2vl3">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2vl3.jpg" alt="2V remote mount manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2VL3-P8SS-HS</p><h3>2V remote mount manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Remote-mount 2-valve manifold for isolation, calibration and block and bleed of gauges, pressure switches and static pressure transmitters.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(M) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2VL3-P8SS-HS" data-desc="2V remote mount manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2ar">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2ar.jpg" alt="2V direct mount manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2AR-P8SS-HS</p><h3>2V direct mount manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Direct-mount 2-valve manifold for connecting the impulse line straight to the transmitter, with isolation and calibration / vent.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2AR-P8SS-HS" data-desc="2V direct mount manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2vtd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2vtd.jpg" alt="2V pipe to flange manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2VTD-P8SS-HS</p><h3>2V pipe to flange manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Pipe-to-flange 2-valve manifold in a single block — female screwed inlet, flanged instrument side — eliminating several joints and parts.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2VTD-P8SS-HS" data-desc="2V pipe to flange manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="2vhd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-2vtd.jpg" alt="2V flange to flange manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 2VHD-P8SS-HS</p><h3>2V flange to flange manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Flange-to-flange 2-valve manifold for direct mounting between process and instrument, with isolation and bleed.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process flange · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="2-Valve Manifolds" data-part="2VHD-P8SS-HS" data-desc="2V flange to flange manifold valve">Add to quote</button></div></div></article></div></section><section class="section alt"><div class="wrap"><div class="two"><div><h2>Specifications</h2><div class="table-wrap"><table><tbody><tr><th scope='row'>Max. pressure</th><td style='white-space:normal'>6,000 psi (413 bar) at 100 °F · 10,000 psi at 77 °F</td></tr><tr><th scope='row'>Seat</th><td style='white-space:normal'>Soft or hard seat</td></tr><tr><th scope='row'>Stem</th><td style='white-space:normal'>Needle (standard), ball tip optional</td></tr><tr><th scope='row'>Gland packing</th><td style='white-space:normal'>PTFE −73 to 210 °C · Graphoil 180 to 540 °C</td></tr><tr><th scope='row'>Materials</th><td style='white-space:normal'>316L/316/304/304L SS, Monel, Inconel, carbon steel, duplex · NACE MR-01-75 for sour gas</td></tr><tr><th scope='row'>Orifice</th><td style='white-space:normal'>4.8 mm</td></tr><tr><th scope='row'>Testing</th><td style='white-space:normal'>Nitrogen at 1,000 psig, max leak 0.1 SCCM; helium leak tested to 1 × 10⁻⁴ ml/s; hydrostatic 1.5 × on request</td></tr></tbody></table></div></div><div><h2>Standard features</h2><ul class="ticks"><li>316/316L stainless steel one-piece forged body, no welds</li><li>Bonnet lock pin resists vibration</li><li>Metal-to-metal bonnet seals, no O-rings</li><li>Compact, with mounting holes</li><li>Dust cap keeps contaminants out</li><li>Non-rotating vee or ball stem tip</li><li>Ends: female NPT, ISO 228/1, MSS SP-99 flange</li><li>100% factory tested</li></ul></div></div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>

<?php include __DIR__ . '/../includes/footer.php'; ?>
