<?php
$title   = '3-Valve Manifold for DP Transmitters | TYA';
$desc    = '3-valve manifolds for differential pressure transmitters, 6,000 or 10,000 psi, direct and remote mount, 6 models. Part numbers, dimensions and quotes.';
$path    = 'manifold-valves/3-valve-manifold';
$section = 'valves';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>manifold-valves/">Manifold valves</a> / 3-Valve Manifolds</div><section class="hero"><div class="wrap">
 <h1>3-Valve Manifolds</h1><div class="rule" aria-hidden="true"></div>
 <p class="lede">Two process isolation valves and an equalizing valve — the most common manifold for differential pressure instruments. Hard seat 10,000 psi or soft seat 6,000 psi, in 316 stainless and alloys.</p><div class="hero-actions"><a class="btn" href="#models">See all models</a><a class="btn ghost" href="<?= BASE ?>assets/catalogs/TYA-Manifold-Valve-Catalog.pdf" data-catalog="manifold">Download the manifold &amp; gauge root valves catalog (PDF)</a></div>
</div></section><section class="section"><div class="wrap"><h2 id="models">Models</h2><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="3vmr-0">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-3vmr-pp.jpg" alt="3V pipe to pipe manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 3VMR-P8SS-HS</p><h3>3V pipe to pipe manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Pipe-to-pipe 3-valve manifold for remote mounting of differential pressure instruments. Two mounting holes for 1/4&quot; bolts; eliminates conventional piping in remote fields.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="3-Valve Manifolds" data-part="3VMR-P8SS-HS" data-desc="3V pipe to pipe manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="3vmr-1">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-3vmr-ff.jpg" alt="3V flange to flange (oval/kidney flanges) manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 3VMR-P8SS-HS</p><h3>3V flange to flange (oval/kidney flanges) manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Flange-to-flange 3-valve manifold for direct or remote mounting of DP transmitters. For remote mounting, two oval / kidney flanges connect the process pipe to the block.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(M) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="3-Valve Manifolds" data-part="3VMR-P8SS-HS" data-desc="3V flange to flange (oval/kidney flanges) manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="3vmr-2">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-3vmr-pf.jpg" alt="3V pipe to flange manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 3VMR-P8SS-HS</p><h3>3V pipe to flange manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Pipe-to-flange 3-valve manifold for direct mounting on DP gauges, transmitters and switches with 54 mm C/C connections; supplied with four 7/16&quot; bolts and two PTFE seals.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="3-Valve Manifolds" data-part="3VMR-P8SS-HS" data-desc="3V pipe to flange manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="3vhd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-3vhd.jpg" alt="3V flange to flange manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 3VHD-P8SS-HS</p><h3>3V flange to flange manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Flange-to-flange 3-valve manifold for direct or remote mounting of DP transmitters, with two process isolation valves and one equalizing valve.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process flange · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="3-Valve Manifolds" data-part="3VHD-P8SS-HS" data-desc="3V flange to flange manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="3vsd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-3vsd.jpg" alt="3V direct mount (angular equalizing bonnet) manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 3VSD-P8SS-HS</p><h3>3V direct mount (angular equalizing bonnet) manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Direct-mount 3-valve manifold with isolate bonnets left and right and an angled equalizing bonnet on top for easy operation.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="3-Valve Manifolds" data-part="3VSD-P8SS-HS" data-desc="3V direct mount (angular equalizing bonnet) manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="3vqd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-3vsd.jpg" alt="3V direct mount (oval flange) manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 3VQD-P8SS-HS</p><h3>3V direct mount (oval flange) manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Direct-mount 3-valve manifold for where a straight valve may foul the instrument; mounted with an oval flange to the 1/2&quot; process pipe or tube.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="3-Valve Manifolds" data-part="3VQD-P8SS-HS" data-desc="3V direct mount (oval flange) manifold valve">Add to quote</button></div></div></article></div></section><section class="section alt"><div class="wrap"><div class="two"><div><h2>Specifications</h2><div class="table-wrap"><table><tbody><tr><th scope='row'>Max. pressure</th><td style='white-space:normal'>6,000 psi (413 bar) at 100 °F · 10,000 psi at 77 °F</td></tr><tr><th scope='row'>Seat</th><td style='white-space:normal'>Soft or hard seat</td></tr><tr><th scope='row'>Stem</th><td style='white-space:normal'>Needle (standard), ball tip optional</td></tr><tr><th scope='row'>Gland packing</th><td style='white-space:normal'>PTFE −73 to 210 °C · Graphoil 180 to 540 °C</td></tr><tr><th scope='row'>Materials</th><td style='white-space:normal'>316L/316/304/304L SS, Monel, Inconel, carbon steel, duplex · NACE MR-01-75 for sour gas</td></tr><tr><th scope='row'>Orifice</th><td style='white-space:normal'>4.8 mm</td></tr><tr><th scope='row'>Testing</th><td style='white-space:normal'>Nitrogen at 1,000 psig, max leak 0.1 SCCM; helium leak tested to 1 × 10⁻⁴ ml/s; hydrostatic 1.5 × on request</td></tr></tbody></table></div></div><div><h2>Standard features</h2><ul class="ticks"><li>316/316L stainless steel one-piece forged body, no welds</li><li>Bonnet lock pin resists vibration</li><li>Metal-to-metal bonnet seals, no O-rings</li><li>Compact, with mounting holes</li><li>Dust cap keeps contaminants out</li><li>Non-rotating vee or ball stem tip</li><li>Ends: female NPT, ISO 228/1, MSS SP-99 flange</li><li>100% factory tested</li></ul></div></div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>

<?php include __DIR__ . '/../includes/footer.php'; ?>
