<?php
$title   = '5-Valve Manifold for Gas Metering | TYA';
$desc    = '5-valve manifolds for differential pressure transmitters and natural gas metering, 6,000 or 10,000 psi. Part numbers, dimensions and distributor quotes.';
$path    = 'manifold-valves/5-valve-manifold';
$section = 'valves';
include __DIR__ . '/../includes/header.php';
?>
<div class="wrap crumbs"><a href="<?= BASE ?>">Home</a> / <a href="<?= BASE ?>manifold-valves/">Manifold valves</a> / 5-Valve Manifolds</div><section class="hero"><div class="wrap">
 <h1>5-Valve Manifolds</h1><div class="rule" aria-hidden="true"></div>
 <p class="lede">Isolation, equalizing and two drain / vent valves for DP instruments that need venting, calibration and system flushing. Hard seat 10,000 psi or soft seat 6,000 psi, in 316 stainless and alloys.</p><div class="hero-actions"><a class="btn" href="#models">See all models</a><a class="btn ghost" href="<?= BASE ?>assets/catalogs/TYA-Manifold-Valve-Catalog.pdf" data-catalog="manifold">Download the manifold &amp; gauge root valves catalog (PDF)</a></div>
</div></section><section class="section"><div class="wrap"><h2 id="models">Models</h2><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="5vmr">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-5vmr.jpg" alt="5V pipe to pipe manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 5VMR-P8SS-HS</p><h3>5V pipe to pipe manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Pipe-to-pipe 5-valve manifold with two process isolation valves, one equalizer and two drain / vent valves, for remote mounting away from the DP instrument.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="5-Valve Manifolds" data-part="5VMR-P8SS-HS" data-desc="5V pipe to pipe manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="5vgr">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-5vgr.jpg" alt="5V pipe to pipe (vertical ports, gas service) manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 5VGR-P8SS-HS</p><h3>5V pipe to pipe (vertical ports, gas service) manifold valve</h3><ul class="specline"><li class="hot">Remote mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Pipe-to-pipe 5-valve manifold with vertical ports for remote mounting to field meters, DP transmitters and chart recorders on gas service.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="5-Valve Manifolds" data-part="5VGR-P8SS-HS" data-desc="5V pipe to pipe (vertical ports, gas service) manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="5vtd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-5vtd.jpg" alt="5V pipe to flange manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 5VTD-P8SS-HS</p><h3>5V pipe to flange manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Pipe-to-flange 5-valve manifold: two isolation, one equalizer and two drain / vent valves in one compact block.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="5-Valve Manifolds" data-part="5VTD-P8SS-HS" data-desc="5V pipe to flange manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="5vhd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-5vhd.jpg" alt="5V flange to flange manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 5VHD-P8SS-HS</p><h3>5V flange to flange manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Flange-to-flange 5-valve manifold for direct or remote mounting of DP transmitters; one-piece bar-stock forged body, stellited two-part stem tip.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process flange · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="5-Valve Manifolds" data-part="5VHD-P8SS-HS" data-desc="5V flange to flange manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="5vqd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-5vqd.jpg" alt="5V direct mount (coplanar) manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 5VQD-P8SS-HS</p><h3>5V direct mount (coplanar) manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Coplanar 5-valve direct-mount manifold for particular transmitter models — compact and easy to operate in minimum space.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument flange · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="5-Valve Manifolds" data-part="5VQD-P8SS-HS" data-desc="5V direct mount (coplanar) manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="5vqr">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-5vqr.jpg" alt="5V direct mount manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 5VQR-P8SS-HS</p><h3>5V direct mount manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>Direct-mount 5-valve manifold with separate vent ports, two isolation and one equalizing valve.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="5-Valve Manifolds" data-part="5VQR-P8SS-HS" data-desc="5V direct mount manifold valve">Add to quote</button></div></div></article><article class="two" style="padding:28px 0;border-top:1px solid var(--steel-line);align-items:center" id="5vgd">
 <div class="p-media" style="min-height:240px"><img src="<?= BASE ?>assets/img/p/mf-5vmr.jpg" alt="5V for differential gauges manifold valve" loading="lazy"></div>
 <div><p class="p-num">Model 5VGD-P8SS-HS</p><h3>5V for differential gauges manifold valve</h3><ul class="specline"><li class="hot">Direct mounting</li><li>1/2" process</li><li>6,000 / 10,000 psi</li></ul>
 <p>5-valve manifold for differential gauges: two female NPT inlets at the bottom and two outlets with rotating nuts on top. 54 mm tap spacing model available.</p><div class="table-wrap"><table><tbody><tr><th scope='row'>Connections</th><td style='white-space:normal'>Process 1/2&quot; NPT(F) · Instrument 1/2&quot; NPT(F) · Drain 1/4&quot; NPT(F)</td></tr></tbody></table></div>
 <div class="cta-row" style="margin-top:12px"><button class="add" data-series="5-Valve Manifolds" data-part="5VGD-P8SS-HS" data-desc="5V for differential gauges manifold valve">Add to quote</button></div></div></article></div></section><section class="section alt"><div class="wrap"><div class="two"><div><h2>Specifications</h2><div class="table-wrap"><table><tbody><tr><th scope='row'>Max. pressure</th><td style='white-space:normal'>6,000 psi (413 bar) at 100 °F · 10,000 psi at 77 °F</td></tr><tr><th scope='row'>Seat</th><td style='white-space:normal'>Soft or hard seat</td></tr><tr><th scope='row'>Stem</th><td style='white-space:normal'>Needle (standard), ball tip optional</td></tr><tr><th scope='row'>Gland packing</th><td style='white-space:normal'>PTFE −73 to 210 °C · Graphoil 180 to 540 °C</td></tr><tr><th scope='row'>Materials</th><td style='white-space:normal'>316L/316/304/304L SS, Monel, Inconel, carbon steel, duplex · NACE MR-01-75 for sour gas</td></tr><tr><th scope='row'>Orifice</th><td style='white-space:normal'>4.8 mm</td></tr><tr><th scope='row'>Testing</th><td style='white-space:normal'>Nitrogen at 1,000 psig, max leak 0.1 SCCM; helium leak tested to 1 × 10⁻⁴ ml/s; hydrostatic 1.5 × on request</td></tr></tbody></table></div></div><div><h2>Standard features</h2><ul class="ticks"><li>316/316L stainless steel one-piece forged body, no welds</li><li>Bonnet lock pin resists vibration</li><li>Metal-to-metal bonnet seals, no O-rings</li><li>Compact, with mounting holes</li><li>Dust cap keeps contaminants out</li><li>Non-rotating vee or ball stem tip</li><li>Ends: female NPT, ISO 228/1, MSS SP-99 flange</li><li>100% factory tested</li></ul></div></div></div></section><?php $whyAlt = false; include INC . 'why-buy.php'; ?>

<?php include __DIR__ . '/../includes/footer.php'; ?>
